In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
# import pickle
import json
pd.options.mode.chained_assignment = None

Companies_arr, seen_brands and unseen_brands json files

In [2]:
with open('companies.json', 'r') as json_file:
    companies_arr = json.load(json_file)

with open('seen_brands.json', 'r') as json_file:
    seen_brands = json.load(json_file)

with open('unseen_brands.json', 'r') as json_file:
    unseen_brands = json.load(json_file)

In [3]:
df1 = pd.read_csv("val.csv")
df2 = pd.read_csv("test.csv")

In [4]:
df1

,id,date,likes,content,username,media,inferred company
0,7,2019-10-24 10:51:03,0,LASU Celebrates New Dawn Of Unbroken Peace As ...,IndependentNGR,[Photo(previewUrl='https://pbs.twimg.com/media...,independent
1,13,2020-03-01 15:48:46,672,"The US-Taliban agreement, which sets into moti...",CNN,[Video(thumbnailUrl='https://pbs.twimg.com/med...,cnn
2,25,2020-07-19 00:07:00,78,Many people are understandably anxious to get ...,MayoClinic,[Photo(previewUrl='https://pbs.twimg.com/media...,mayo clinic
3,27,2018-09-26 16:42:17,961,ALSO NOW (yes it's wild here today): Sen Merkl...,LisaDNews,[Photo(previewUrl='https://pbs.twimg.com/media...,desjardins
4,39,2020-03-11 20:15:08,4,Toyota Motor North America Chief Diversity Off...,ToyotaSD,[Photo(previewUrl='https://pbs.twimg.com/media...,toyota
...,...,...,...,...,...,...,...
29922,299939,2019-04-16 08:57:17,2151,Start em young üí™üèæ <hyperlink>,SonnyBWilliams,[Video(thumbnailUrl='https://pbs.twimg.com/ext...,williams
29923,299954,2018-05-31 11:41:10,44,"Nearly 15 years after leaving public office, f...",TheCurrentCBC,[Photo(previewUrl='https://pbs.twimg.com/media...,cbc
29924,299959,2019-02-01 15:24:27,16,Sparks are set to fly when speedsters Rabz Max...,CheetahsRugby,[Photo(previewUrl='https://pbs.twimg.com/media...,toyota
29925,299969,2018-11-07 15:14:56,166,"""We can help #cities help manage their tourism...",MastercardNews,[Photo(previewUrl='https://pbs.twimg.com/media...,mastercard
29926,299988,2018-06-05 16:52:54,115,From <mention> <hyperlink>,officialmcafee,[Photo(previewUrl='https://pbs.twimg.com/media...,mcafee

In [5]:
df3 = df2.copy()
df3 = df3.iloc[:30000]

In [6]:
df3

,id,date,likes,content,username,media,inferred company
0,5,2018-10-19 14:30:46,41,Congratulations to Pauletha Butts of <mention>...,BGISD,[Photo(previewUrl='https://pbs.twimg.com/media...,independent
1,12,2020-11-18 00:07:02,0,#NetZeroHomes: learn the best way to get to ze...,MitsubishiHVAC,[Photo(previewUrl='https://pbs.twimg.com/media...,trane
2,23,2018-09-11 14:23:02,120,"Tournaments come and go, but the pictures are ...",GettySport,[Photo(previewUrl='https://pbs.twimg.com/media...,getty images
3,31,2020-11-10 03:00:26,567,Monster Hunter Rise Concept Art: Great Izuchi....,MHinfo_en,[Photo(previewUrl='https://pbs.twimg.com/media...,monster
4,32,2018-11-29 22:11:56,1,"With our #SalesDevelopmentProgram, you'll lear...",UnitedRentals,[Photo(previewUrl='https://pbs.twimg.com/media...,united rentals
...,...,...,...,...,...,...,...
29995,152191,2020-07-19 11:48:33,1,"COVID-19: Osun Records 4 New Cases, Discharges...",IndependentNGR,[Photo(previewUrl='https://pbs.twimg.com/media...,independent
29996,152193,2019-01-31 11:44:32,1911,This is stunning\n\nHuge #ClimateStrike protes...,GreenpeaceEU,[Video(thumbnailUrl='https://pbs.twimg.com/ext...,greenpeace
29997,152213,2020-09-01 16:35:12,2,"OTD, 1964: Masanori Murakami becomes the first...",ToyotaFanZone,[Photo(previewUrl='https://pbs.twimg.com/media...,toyota
29998,152214,2020-07-13 08:32:04,2036,One last spin around the Red Bull Ring? ü§ò Get ...,redbullracing,[Video(thumbnailUrl='https://pbs.twimg.com/med...,red bull
29999,152221,2018-06-30 17:41:30,327,We‚Äôre just so happy we met youuu! Maraming sal...,mmprideorg,[Video(thumbnailUrl='https://pbs.twimg.com/ext...,metro

In [7]:
merged_df = pd.concat([df1, df3])
merged_df = merged_df.sort_values(by='id')
merged_df = merged_df.reset_index(drop=True)
merged_df

,id,date,likes,content,username,media,inferred company
0,5,2018-10-19 14:30:46,41,Congratulations to Pauletha Butts of <mention>...,BGISD,[Photo(previewUrl='https://pbs.twimg.com/media...,independent
1,7,2019-10-24 10:51:03,0,LASU Celebrates New Dawn Of Unbroken Peace As ...,IndependentNGR,[Photo(previewUrl='https://pbs.twimg.com/media...,independent
2,12,2020-11-18 00:07:02,0,#NetZeroHomes: learn the best way to get to ze...,MitsubishiHVAC,[Photo(previewUrl='https://pbs.twimg.com/media...,trane
3,13,2020-03-01 15:48:46,672,"The US-Taliban agreement, which sets into moti...",CNN,[Video(thumbnailUrl='https://pbs.twimg.com/med...,cnn
4,23,2018-09-11 14:23:02,120,"Tournaments come and go, but the pictures are ...",GettySport,[Photo(previewUrl='https://pbs.twimg.com/media...,getty images
...,...,...,...,...,...,...,...
59922,299939,2019-04-16 08:57:17,2151,Start em young üí™üèæ <hyperlink>,SonnyBWilliams,[Video(thumbnailUrl='https://pbs.twimg.com/ext...,williams
59923,299954,2018-05-31 11:41:10,44,"Nearly 15 years after leaving public office, f...",TheCurrentCBC,[Photo(previewUrl='https://pbs.twimg.com/media...,cbc
59924,299959,2019-02-01 15:24:27,16,Sparks are set to fly when speedsters Rabz Max...,CheetahsRugby,[Photo(previewUrl='https://pbs.twimg.com/media...,toyota
59925,299969,2018-11-07 15:14:56,166,"""We can help #cities help manage their tourism...",MastercardNews,[Photo(previewUrl='https://pbs.twimg.com/media...,mastercard
59926,299988,2018-06-05 16:52:54,115,From <mention> <hyperlink>,officialmcafee,[Photo(previewUrl='https://pbs.twimg.com/media...,mcafee

In [8]:
final_df = merged_df.copy()

In [9]:
final_df.to_csv("60k_df_Task2.csv")

In [21]:
def unseen_brand(likes, input_date, inp_unseen_brand, k=5):
    input_date = datetime.strptime(input_date, '%Y-%m-%d %H:%M:%S')
    six_months = timedelta(days=30*6)
    start_date = input_date - six_months
    end_date = input_date
    final_df['date'] = pd.to_datetime(final_df['date'])
    
    filtered_df = final_df[(final_df['date'] >= start_date) & (final_df['date'] <= end_date)]
    
    if filtered_df.empty:
        print(f"No matching rows found for {input_date}")
        return None
    
    companies=[]
    for row in companies_arr:
        if inp_unseen_brand in row:
            companies=row
    
    filtered2_df = filtered_df[filtered_df['inferred company'].isin(companies)]
    
    filtered2_df['likes_distance'] = abs(filtered2_df['likes'] - likes)
    top_k_df = filtered2_df.nsmallest(k, 'likes_distance')
    
    return top_k_df.drop(columns=['likes_distance'])

In [11]:
def unseen_period(input_company_name,input_likes,k=5):
    matching_rows = final_df[final_df['inferred company'] == input_company_name]

    if matching_rows.empty:
        print(f"No matching rows found for {input_company_name}")
        return None

    df_new = matching_rows.copy()

    df_new['likes_diff'] = abs(final_df['likes'] - input_likes)

    df_sorted = df_new.sort_values(by='likes_diff')

    if(len(df_sorted)>=k):
        return df_sorted[:k]
    else:
        return df_sorted

Go through each element of the dataframe. If the company is seen, then run unseen_period to generate the extra columns. If company is unseen, run unseen_brands to generate the extra columns. Those columns together with these are passed into the model for inference, we'll compare the output of the model with the content column.

In [12]:
type(unseen_brands),type(seen_brands)

(function, list)

In [13]:
df = pd.read_csv("60k_df_Task2.csv")

In [14]:
df['inferred company'][10]

'cnn'

In [15]:
df['KNN 1'] = ""
df['KNN 2'] = ""
df['KNN 3'] = ""

In [19]:
for i in range(len(df)):
    brand = df['inferred company'][i]
    if(i%500==0):    
        print(i)
    if brand in seen_brands:
        likes = df['likes'][i]
        df_output = unseen_period(brand,likes,4)
        quadruplet = df_output['content'].reset_index(drop=True).tolist()
        content = df['content'][i]
        # print(quadruplet)
        triplet = []
        for q in quadruplet:
            if(q!=content):
                triplet.append(q)
        # print(triplet)
        try:
            df['KNN 1'][i] = triplet[0]
            df['KNN 2'][i] = triplet[1]
            df['KNN 3'][i] = triplet[2]
        except:
            print(i)
            print(pd.Series(triplet))
        # break
    elif brand in unseen_brands:
        likes = df['likes'][i]
        date = df['date'][i]
        df_output = unseen_brands(likes, date, brand, 3)
        triplet = df_output['content'].reset_index(drop=True)
        df['KNN 1'][i] = triplet[0]
        df['KNN 2'][i] = triplet[1]
        df['KNN 3'][i] = triplet[2]

0
500
1000
1303
0    Clyde Christensen spent years as Peyton Mannin...
dtype: object
1500
1624
0    "A lot of these teams can't dodge the dogshit....
dtype: object
1711
0    We are in week 17 of an NFL season no one thou...
1    Hey.. put in your $10 RISK FREE Same Game Parl...
dtype: object
2000
2290
0    Today marks 60 years at our world headquarters...
1    On Tuesday, <mention> announced the newest ath...
dtype: object
2500
3000
3232
0    So proud to announce our endorsement by ‚Å¶<ment...
1    Sometimes the best Valentines have 4 paws. Get...
dtype: object
3351
0    Tomorrow is part 3 of our Remote User Interfac...
1    How does neuroscience, #AI, behavior and techn...
dtype: object
3500
3825
0    I like the Mike McCarthy hire for the #Cowboys...
1    "For a little guy he has a very, very strong a...
dtype: object
3979
0    Q: <mention> are you going to sponsor a car in...
dtype: object
4000
4457
0    <mention> Him, believe it or not, was was Epst...
dtype: object
4500
4712
0    Q: <mention> are you going to sponsor a car in...
dtype: object
5000
5019
0    Today marks 60 years at our world headquarters...
1    Meet the Cereal Squad - six collectible toys t...
dtype: object
5132
0    üó£LAST CALL TO GET IN THE #GROAT... $5, <hyperl...
1    Breaking down what has made the #Chiefs defens...
dtype: object
5500
5842
Series([], dtype: float64)

/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/ipykernel_14919/3273360241.py:22: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series(triplet))

5901
0                Happy #WorldSeaTurtleDay! <hyperlink>
1    Today is the 75th anniversary of when the Nazi...
dtype: object
6000
6004
0    Some incredible guests we'll chat with to get ...
1    Joining us now to chat about all the NFL actio...
dtype: object
6500
7000
7181
0    This is the week..\n\nThis is the week my <men...
1    The #Patriots square off with an old foe tonig...
dtype: object
7500
7530
0    McAfee 2020 T-shirts and Hoodies coming soon. ...
1               üó£ LET‚ÄôS GOOOO #ForTheBrand <hyperlink>
dtype: object
8000
8500
9000
9037
0                <mention> <mention> Field <hyperlink>
1    Hour 2 LIVE from Florida starts now #PatMcAfee...
dtype: object
9500
9910
0    "It was a challenge but the challenge is the e...
1    <mention> <mention> <mention> <mention> These ...
dtype: object
10000
10065
0    It‚Äôs the day we‚Äôve been waiting all year for; ...
1    <mention> Thanks for honoring our Vets! -JC <h...
dtype: object
10500
10567
0    LET‚ÄôS HAVE A TUESDAY\n\nDay 2 of #PatMcAfeeSho...
1    We are in week 17 of an NFL season no one thou...
dtype: object
10934
0    üó£ LET‚ÄôS TALK ABOUT LIFE ON <mention>... 1-833-...
1    Can we please talk about that Christmas card w...
dtype: object
11000
11327
0    Clyde Christensen spent years as Peyton Mannin...
dtype: object
11500
11641
0    Burger (Scorpio) &amp; fries (Sagittarius) so ...
1    A Dutch pensioner has started a legal battle t...
dtype: object
11703
0    "A lot of these teams can't dodge the dogshit....
dtype: object
11818
0    Some incredible guests we'll chat with to get ...
1    Joining us now to chat about all the NFL actio...
dtype: object
12000
12051
0    I like the Mike McCarthy hire for the #Cowboys...
1    "For a little guy he has a very, very strong a...
dtype: object
12091
0    "To say that what happened with me and USC was...
dtype: object
12211
0    A lion‚Äôs roar can travel 5 miles and reach 114...
1                Happy #WorldSeaTurtleDay! <hyperlink>
dtype: object
12500
12670
0    Hour 2 LIVE from Florida starts now #PatMcAfee...
1    More #QuestionsFromTheYouTube about a potentia...
dtype: object
13000
13220
0    Tomorrow is part 3 of our Remote User Interfac...
1    How does neuroscience, #AI, behavior and techn...
dtype: object
13375
0    With us now the host of <mention> a legend in ...
1    Q: Q:What is the greatest thing Sally McAfee e...
dtype: object
13500
14000
14147
0    <mention> Him, believe it or not, was was Epst...
dtype: object
14500
14656
0    "The biggest most glaring problem for Tampa wo...
1    Coming up LIVE! Hall of Fame QB <mention> call...
dtype: object
15000
15260
0    üó£ LET‚ÄôS TALK ABOUT LIFE ON <mention>... 1-833-...
1    Can we please talk about that Christmas card w...
dtype: object
15500
15660
0    <mention> This is a massive moment for you Ita...
dtype: object
15871
0    When cybersecurity professionals give relation...
1    <mention> But I've enjoyed every single incarc...
dtype: object
15968
0    <mention> <mention> Hahaha.. no no.. still ver...
1    Breaking down the #CFBPlayoff rankings with <m...
dtype: object
16000
16114
0    "The whole thing is why.. Why ya'll keep doing...
1    Joining us now former <mention> Guard for 11 y...
dtype: object
16373
0                Happy #WorldSeaTurtleDay! <hyperlink>
1    Today is the 75th anniversary of when the Nazi...
dtype: object
16500
16791
0          We all know someone like this. <hyperlink>
1    <mention> Keep them eyes open cuzzie <hyperlink>
dtype: object
17000
17223
0          Polls are closed in #MI03! üá∫üá∏üá∫üá∏ <hyperlink>
1    Sometimes the best Valentines have 4 paws. Get...
dtype: object
17383
0    Hey team.. let‚Äôs talk about your weekend on <m...
1    The <hyperlink> project was conceived, designe...
dtype: object
17500
17717
0    "It was a challenge but the challenge is the e...
1    <mention> <mention> <mention> <mention> These ...
dtype: object
18000
18017
0    <mention> <mention> Can‚Äôt. Wait.\n\nSide note ...
1    I just gave a talk on science and skepticism i...
dtype: object
18276
0    Die hard #Steeler fan <mention> apologizes to ...
1    Tampa Bay #Buccaneers QB coach Clyde Christens...
dtype: object
18500
18904
0    My capture by the Yanomamo Tribe -\n\nOf the u...
1    I like the back to back games this weekend I l...
dtype: object
19000
19231
0    With us now senior #NFL reporter for <mention>...
1       Limited edition üî•~&gt; <hyperlink> <hyperlink>
dtype: object
19380
0    Because changing nothing can change everything...
dtype: object
19500
20000
20322
0    MPs reject Theresa May's Brexit deal in the la...
1    Happy 90th birthday, Thomas Sowell. üéÇ <hyperlink>
dtype: object
20332
0    #PatMcAfeeShowLIVE coming in a couple minutes\...
1    "If you're struggling and you have <mention> i...
dtype: object
20500
20907
0    With us now senior #NFL reporter for <mention>...
1       Limited edition üî•~&gt; <hyperlink> <hyperlink>
dtype: object
21000
21500
21718
0    As a company, we are transforming, but we cann...
dtype: object
22000
22086
0    Burger (Scorpio) &amp; fries (Sagittarius) so ...
1    Scorpios pretending they have something to do ...
dtype: object
22353
Series([], dtype: float64)

/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/ipykernel_14919/3273360241.py:22: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series(triplet))

22500
22500
0    This is the week..\n\nThis is the week my <men...
1    The #Patriots square off with an old foe tonig...
dtype: object
22512
0    Our 16th "If My Life Was a Movie" award goes t...
1            <mention> This was brilliant. <hyperlink>
dtype: object
22646
Series([], dtype: float64)

/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/ipykernel_14919/3273360241.py:22: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series(triplet))

22820
0    Taking a moment to say #ThanksforDelivering to...
dtype: object
23000
23500
24000
24500
24990
0    "He's like my big brother. So I thought I knew...
1    Chatting with #Colts legend <mention> on <ment...
dtype: object
25000
25500
26000
26500
27000
27500
27664
0    We are honoured to be on TIME's inaugural list...
dtype: object
27760
0    I like that Coack K is trying to tame the Came...
1    "It was one of the hardest conversations I've ...
dtype: object
28000
28500
29000
29167
0    Left: me in captivity. Right: Ancient Navajo b...
1    "I think the #Bengals should take Joe Burrow a...
dtype: object
29291
0    It‚Äôs the day we‚Äôve been waiting all year for; ...
1    <mention> Thanks for honoring our Vets! -JC <h...
dtype: object
29500
29751
0          We all know someone like this. <hyperlink>
1    <mention> Keep them eyes open cuzzie <hyperlink>
dtype: object
30000
30500
30605
0    üé∂ For those who come to San Francisco\nSummert...
dtype: object
31000
31418
0    Clyde Christensen spent years as Peyton Mannin...
dtype: object
31500
32000
32086
Series([], dtype: float64)

/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/ipykernel_14919/3273360241.py:22: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series(triplet))

32415
0    Calling all #STEMstudents! We want to see your...
dtype: object
32500
32998
0    My capture by the Yanomamo Tribe -\n\nOf the u...
1    I like the back to back games this weekend I l...
dtype: object
33000
33402
0    Q: <mention> are you going to sponsor a car in...
dtype: object
33500
34000
34500
35000
35252
0    Itangazo riturutse mu Biro bya Minisitiri w'In...
1                  ‚ÄúYou should SMILE more" <hyperlink>
dtype: object
35500
35767
0    Joining us now on the #McAfeeAndHawk Sports Ta...
1    #NBA insider <mention> gives us the latest on ...
dtype: object
36000
36500
37000
37415
0    Our 16th "If My Life Was a Movie" award goes t...
1            <mention> This was brilliant. <hyperlink>
dtype: object
37500
38000
38010
0    So proud to announce our endorsement by ‚Å¶<ment...
1          Polls are closed in #MI03! üá∫üá∏üá∫üá∏ <hyperlink>
dtype: object
38500
39000
39292
0    The New Yorker hoy: <hyperlink>
dtype: object
39500
39610
0    On World #NoTobacco Day, find out why we‚Äôre tr...
dtype: object
40000
40243
0    #PatMcAfeeShowLIVE coming in a couple minutes\...
1    "If you're struggling and you have <mention> i...
dtype: object
40500
41000
41220
Series([], dtype: float64)

/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/ipykernel_14919/3273360241.py:22: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series(triplet))

41500
41508
0    CEO Kasana events welcomes all present for the...
1    Get the best smartphone deals on MTN! Purchase...
dtype: object
41702
0    A lot of training camp injuries are popping up...
1    "I really think that we're going to find out s...
dtype: object
41926
0    "He's like my big brother. So I thought I knew...
1    Chatting with #Colts legend <mention> on <ment...
dtype: object
42000
42040
0    Georgia loves rabbits &amp; wants to be a rabb...
1        #Spay &amp; #Neuter also means... <hyperlink>
dtype: object
42158
0    General Bob Carpenter <mention> has not given ...
dtype: object
42500
43000
43500
43759
0    "The biggest most glaring problem for Tampa wo...
1    Coming up LIVE! Hall of Fame QB <mention> call...
dtype: object
44000
44264
0    <mention> <mention> Can‚Äôt. Wait.\n\nSide note ...
1    I just gave a talk on science and skepticism i...
dtype: object
44500
44538
0    "To say that what happened with me and USC was...
dtype: object
44550
0    <mention> This is a massive moment for you Ita...
dtype: object
45000
45122
0     What do you think?\n\nFrom <mention> <hyperlink>
1    Our latest addition, #MVISION EDR, means highe...
dtype: object
45500
45942
0    Police officers filmed playing hopscotch in De...
1    MPs reject Theresa May's Brexit deal in the la...
dtype: object
46000
46087
0    Clyde Christensen spent years as Peyton Mannin...
dtype: object
46233
0    I don't know what Bron Bron was doing last nig...
1    The 49ers have had the 2nd easiest schedule in...
dtype: object
46241
0     <mention> Word. I've had experience. <hyperlink>
1    We asked, you answered #PollThePeople who was ...
dtype: object
46340
0    Did you know that young moray eels are transpa...
1    In recognition of his leadership in the protec...
dtype: object
46425
0    Pretty sure <mention> and I just made the perf...
1    Everybody knows I'm an <mention> guy.. but tha...
dtype: object
46429
0    "The biggest most glaring problem for Tampa wo...
1    Coming up LIVE! Hall of Fame QB <mention> call...
dtype: object
46500
46791
0    Some incredible guests we'll chat with to get ...
dtype: object
46942
0    <mention> <mention> Hahaha.. no no.. still ver...
1    Breaking down the #CFBPlayoff rankings with <m...
dtype: object
47000
47196
0    Q: <mention> are you going to sponsor a car in...
dtype: object
47317
Series([], dtype: float64)

/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/ipykernel_14919/3273360241.py:22: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series(triplet))

47440
0    I just did my civic duty! ... provisionally .....
dtype: object
47486
0    "On collective negotiations the public sides w...
1    Tom Brady is still dominating the headlines. W...
dtype: object
47500
47651
0    We thank you all for joining our incredible In...
1    Stop and take in the view.\n\nüì∑: Shared by Tho...
dtype: object
47739
Series([], dtype: float64)

/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/ipykernel_14919/3273360241.py:22: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series(triplet))

47849
0    <mention> This is a massive moment for you Ita...
dtype: object
47880
0    MY <mention> FOR THIS WEEK IS A GUARANTEE #PAT...
1    The field situation at MetLife is very interes...
dtype: object
48000
48261
0    With us now 3X Super Bowl champ former Dallas ...
1    Are the #49ers developing a master plan to acq...
dtype: object
48386
0    Celebrating the launch of our non-stop flight ...
dtype: object
48500
48555
0    "To say that what happened with me and USC was...
dtype: object
48778
0    I just did my civic duty! ... provisionally .....
dtype: object
48897
0    Our 16th "If My Life Was a Movie" award goes t...
1            <mention> This was brilliant. <hyperlink>
dtype: object
48921
0    "The whole thing is why.. Why ya'll keep doing...
1    Joining us now former <mention> Guard for 11 y...
dtype: object
49000
49221
0    "The #FutureWorkforce requires business leader...
1    We're clearing a path to insights at #WEF18, t...
dtype: object
49354
0    üó£ LET‚ÄôS TALK ABOUT LIFE ON <mention>... 1-833-...
1    Can we please talk about that Christmas card w...
dtype: object
49500
49603
0    Everybody knows I'm an <mention> guy.. but tha...
1    The John and Ricky Show - "The Propper Attribu...
dtype: object
50000
50234
0    This is the week..\n\nThis is the week my <men...
1    The #Patriots square off with an old foe tonig...
dtype: object
50380
0    Die hard #Steeler fan <mention> apologizes to ...
1    Tampa Bay #Buccaneers QB coach Clyde Christens...
dtype: object
50500
50995
0    A lot of training camp injuries are popping up...
1    "I really think that we're going to find out s...
dtype: object
51000
51500
51682
0    <mention> <mention> Can‚Äôt. Wait.\n\nSide note ...
1    I just gave a talk on science and skepticism i...
dtype: object
51898
0    With us now a former teammate of mine and big ...
1    "There's so much we don't know about players. ...
dtype: object
52000
52238
Series([], dtype: float64)

/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/ipykernel_14919/3273360241.py:22: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series(triplet))

52500
52845
0    Hey team.. let‚Äôs talk about your weekend on <m...
1    The <hyperlink> project was conceived, designe...
dtype: object
53000
53198
0    "A lot of these teams can't dodge the dogshit....
dtype: object
53254
Series([], dtype: float64)

/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/ipykernel_14919/3273360241.py:22: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series(triplet))

53500
53572
0    #PatMcAfeeShowLIVE coming in a couple minutes\...
1    "If you're struggling and you have <mention> i...
dtype: object
53737
0    Hour 2 LIVE from Florida starts now #PatMcAfee...
1    More #QuestionsFromTheYouTube about a potentia...
dtype: object
54000
54070
0    I just did my civic duty! ... provisionally .....
dtype: object
54125
0    <mention> <mention> Hahaha.. no no.. still ver...
1    Breaking down the #CFBPlayoff rankings with <m...
dtype: object
54500
54685
0    What‚Äôs up? Need you on the show today.. debuti...
1    I love what <mention> was doing last night..\n...
dtype: object
54705
0    With us now the host of <mention> a legend in ...
1    Q: Q:What is the greatest thing Sally McAfee e...
dtype: object
54760
0    Q: <mention> are you going to sponsor a car in...
dtype: object
54862
0     <mention> Word. I've had experience. <hyperlink>
1    We asked, you answered #PollThePeople who was ...
dtype: object
55000
55421
0    Hey team.. let‚Äôs talk about your weekend on <m...
1    The <hyperlink> project was conceived, designe...
dtype: object
55462
0    <mention> <mention> That‚Äôs just because he doe...
dtype: object
55500
55914
0    Hey team.. let‚Äôs talk about your weekend on <m...
1    The <hyperlink> project was conceived, designe...
dtype: object
56000
56236
0     What do you think?\n\nFrom <mention> <hyperlink>
1    Our latest addition, #MVISION EDR, means highe...
dtype: object
56500
56557
0    General Bob Carpenter <mention> has not given ...
dtype: object
56684
0    Meet the Cereal Squad - six collectible toys t...
1    On Tuesday, <mention> announced the newest ath...
dtype: object
56978
0    <mention> Him, believe it or not, was was Epst...
dtype: object
57000
57277
0    "On collective negotiations the public sides w...
1    Tom Brady is still dominating the headlines. W...
dtype: object
57352
0    <mention> <mention> Can‚Äôt. Wait.\n\nSide note ...
1    I just gave a talk on science and skepticism i...
dtype: object
57491
0    Q: <mention> are you going to sponsor a car in...
dtype: object
57500
57622
0    <mention> <mention> That‚Äôs just because he doe...
dtype: object
57711
0    Did you know that young moray eels are transpa...
dtype: object
57780
0    General Bob Carpenter <mention> has not given ...
dtype: object
57890
0    <mention> I gave orders - not to be disturbed....
1              <mention> Behind the scenes <hyperlink>
dtype: object
57966
0    With us now 3X Super Bowl champ former Dallas ...
1    Are the #49ers developing a master plan to acq...
dtype: object
58000
58068
Series([], dtype: float64)

/var/folders/hr/cn8gd6d15xv_6m22yptdtyhw0000gn/T/ipykernel_14919/3273360241.py:22: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(pd.Series(triplet))

58151
0    Some incredible guests we'll chat with to get ...
dtype: object
58174
0    With us now a former teammate of mine and big ...
1    "There's so much we don't know about players. ...
dtype: object
58500
59000
59066
0    #PatMcAfeeShowLIVE coming in a couple minutes\...
1    "If you're struggling and you have <mention> i...
dtype: object
59194
0    "It was a challenge but the challenge is the e...
1    <mention> <mention> <mention> <mention> These ...
dtype: object
59303
0    We‚Äôre thrilled to announce our new strategic p...
dtype: object
59378
0    I like that Coack K is trying to tame the Came...
1    "It was one of the hardest conversations I've ...
dtype: object
59500
59631
0          We all know someone like this. <hyperlink>
1    <mention> Keep them eyes open cuzzie <hyperlink>
dtype: object
59747
0    <mention> <mention> Can‚Äôt. Wait.\n\nSide note ...
1    I just gave a talk on science and skepticism i...
dtype: object
59926
0    With us now senior #NFL reporter for <mention>...
1       Limited edition üî•~&gt; <hyperlink> <hyperlink>
dtype: object

In [20]:
df.to_csv("with_knn_columns.csv")